
from pygr import worldbase

def main():
    """This function returns the argument.
    Example:
    >>> main()
    ['Bio.Seq.Genome.YEAST.sacCer1', 'Bio.Seq.Genome.YEAST.sacCer1.fasta', '__doc__.Bio.Seq.Genome.YEAST.sacCer1', '__doc__.Bio.Seq.Genome.YEAST.sacCer1.fasta']
    INFO downloader.download_unpickler: Beginning download of http://biodb.bioinformatics.ucla.edu/GENOMES/sacCer1/chromFa.zip to /Users/leec/projects/pygr/tests/sacCer1.zip...
    ...
INFO downloader.download_monitor: downloaded 385024 bytes (10.2%)...
INFO downloader.download_monitor: downloaded 770048 bytes (20.3%)...
INFO downloader.download_monitor: downloaded 1155072 bytes (30.5%)...
INFO downloader.download_monitor: downloaded 1540096 bytes (40.7%)...
INFO downloader.download_monitor: downloaded 1925120 bytes (50.9%)...
INFO downloader.download_monitor: downloaded 2310144 bytes (61.0%)...
INFO downloader.download_monitor: downloaded 2695168 bytes (71.2%)...
INFO downloader.download_monitor: downloaded 3080192 bytes (81.4%)...
INFO downloader.download_monitor: downloaded 3465216 bytes (91.6%)...
INFO downloader.download_unpickler: Download done.
INFO downloader.uncompress_file: unzipping C:\Users\Chintan\projects\
ets Using Worldbase\sacCer1.zip...
DEBUG seqdb._create_seqLenDict: Building sequence length index...
    17
    230208
    """
    print worldbase.dir('YEAST', matchType='r', download=True)

    yeast = worldbase.Bio.Seq.Genome.YEAST.sacCer1(download=True)

    print len(yeast)

    print yeast.keys

    print len(yeast['chr1'])

if __name__ == '__main__':
        import doctest
        doctest.testmod()



